_BASE_: "/mnt/maths/mt601/centermask2/Base-CenterMask-VoVNet.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_fcos_vovnet_fpn_backbone"
    FREEZE_AT: 0
  VOVNET:
    CONV_BODY : "V-99-eSE"
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"  
  MASK_ON: True
  MASKIOU_ON: True
  FCOS:
    NUM_CLASSES: 3
    PRE_NMS_TOPK_TRAIN: 2000
    PRE_NMS_TOPK_TEST: 4000
    POST_NMS_TOPK_TRAIN: 15000
    POST_NMS_TOPK_TEST: 3000
  RPN:
    BATCH_SIZE_PER_IMAGE: 3000
    POST_NMS_TOPK_TEST: 3000
    POST_NMS_TOPK_TRAIN: 3000
  ROI_HEADS:
    NUM_CLASSES: 3
    BATCH_SIZE_PER_IMAGE: 3000
    NAME: "CenterROIHeads"
    IN_FEATURES: ["p3", "p4", "p5"]
  ROI_MASK_HEAD:
    NAME: "SpatialAttentionMaskHead"
    ASSIGN_CRITERION: "ratio"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  RETINANET:
    NUM_CLASSES: 1
    TOPK_CANDIDATES_TEST: 3000
  PIXEL_MEAN: [128, 128, 128]
  PIXEL_STD: [11.578, 11.578, 11.578]
SOLVER:
  STEPS: (5000, 7000)
  MAX_ITER: 10000
  IMS_PER_BATCH: 4
  BASE_LR: 5e-3
  WARMUP_ITERS: 500
  CHECKPOINT_PERIOD: 2500
DATASETS:
  TRAIN: ("sartorius_train",)
  TEST: ("sartorius_val",)
  PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
INPUT:
  MIN_SIZE_TRAIN: (440, 480, 520, 560, 580, 620)
TEST:
  DETECTIONS_PER_IMAGE: 1000 # 1000
DATALOADER:
  NUM_WORKERS: 12